### ISSUE TITLE
Masonry Methods

### ISSUE THREAD

**Issue by HamishBuckley** [shayanypn/ember-cli-masonry-grid#1]
Just wondering if there is any way to call a Masonry method specifically "reloadItems". My use case is making a DOM change in an action that isn't causing Masonry to reload?
Cheers

**Comment by shayanypn** [comment]
@HamishBuckley  Thank u for you issue, I just add the events to the module
Please refer to [this](http://ember-masonry.shayanypn.ir/demo), Under tab "Use Events" i put an example
