### ISSUE TITLE
Rerendering on any change

### ISSUE THREAD

**Issue by brancusi** [shayanypn/ember-cli-masonry-grid#3]
First off, thanks for posting this addon, it's really nice.

I have cards being displayed and anytime I change data, the cards are rerendered and the transitions run. If I set `transitionDuration: 0` there is jitter.

Wondering if you have experienced this.

Thanks

**Comment by shayanypn** [comment]
@brancusi  Thank u.
Sorry i just test the `transitionDuration`, it works properly .
Please put some code, or tell more about your testing environment.
